language: ruby
dist: trusty
sudo: false
cache:
  bundler: true
rvm:
  - 2.5.5
env:
  matrix:
    - SOLIDUS_BRANCH=v2.6
    - SOLIDUS_BRANCH=v2.7
    - SOLIDUS_BRANCH=v2.8
    - SOLIDUS_BRANCH=v2.9
    - SOLIDUS_BRANCH=master
matrix:
  fast_finish: true
  allow_failures:
    - env: SOLIDUS_BRANCH=master
script: bundle exec rake
